name: Build ChOma

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenSSL (macOS Build Only)
        run: |
          brew install openssl@3

      - name: Build for macOS
        run: |
          OPENSSL_PREFIX=$(brew --prefix openssl@3)
          
          make DISABLE_TESTS=1 \
            CFLAGS="-I$OPENSSL_PREFIX/include" \
            LDFLAGS="-L$OPENSSL_PREFIX/lib -lcrypto -framework CoreFoundation"

      - name: Clean Workspace Object Files
        run: |
          make clean

      - name: Build for iOS
        run: |
          make TARGET=ios DISABLE_TESTS=1 \
            LDFLAGS="-framework CoreFoundation"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: choma-binaries
          path: output/
